WIP: Add support for VPP 22.10
PANTHEONtech/StoneWork pull request #70
Opened 2022-10-26 16:48 UTC by pemoticak

2022-11-23 13:33 UTC, fgschwan requested changes
Please run also `make test-vpp-plugins` to check compatibility of custom VPP plugins with new VPP version (ideally it should be also part of https://github.com/PANTHEONtech/StoneWork/blob/main/docs/UPDATE_PROCEDURE.md for cases when VPP plugins change or VPP is upgraded). 
Currently this is not part of `make test`. This is due to long time needed for building of VPP  with given custom VPP plugins from scratch. That is needed as setup for running the tests.

2022-11-24 09:02 UTC, pemoticak commented
> Please run also `make test-vpp-plugins`

Ran it and all tests passed. Additionally the output of `docker build` when building the test image is now piped to the console so that the test results are visible (otherwise docker trucates the output).

> ideally it should be also part of https://github.com/PANTHEONtech/StoneWork/blob/main/docs/UPDATE_PROCEDURE.md

Added a short paragraph about running these custom VPP plugin tests.

2022-11-24 10:00 UTC, fgschwan approved these changes

2022-11-25 07:49 UTC, ondrej-fabry approved these changes

2022-11-25 07:49 UTC, merged